From golang
MAINTAINER suresh vv <https://github.com/suresh-baswa>
# get the code from github
RUN go get github.com/suresh-baswa/suresh
# create a working directory
WORKDIR go/src/app
# copy files
RUN cp go/src/github.com/suresh-baswa/suresh/RestServiceExample.go /go/src/app
# gooo build
RUN go build /go/src/app/RestServiceExample.go
# run the binary
cmd ["/go/src/app/RestServiceExample"]